/*
 * Copyright 2012 Ivashin Alexey <ivashin.alexei@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.fedul0x.ip.view;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.text.DateFormatter;
import ru.fedul0x.ip.dataaccess.DataSourceHibernate;
import ru.fedul0x.ip.dataaccess.DataSourceRepository;
import ru.fedul0x.ip.dataaccess.dataobject.Patient;
import ru.fedul0x.ip.view.component.SexComboBoxModel;

/**
 *
 * @author Ivashin Alexey <ivashin.alexei@gmail.com>
 */
public class PatienAddFrame extends javax.swing.JFrame {

    /**
     * Creates new form PatienAddFrame
     */
    public PatienAddFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        firstNameTextField = new javax.swing.JTextField();
        middleNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        DateFormat date = new SimpleDateFormat("dd MMMM yyyy, EEEE");
        DateFormatter formatter = new DateFormatter(date);
        formatter.setAllowsInvalid(false);
        formatter.setOverwriteMode(true);
        birthdayDateFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        registrationDateFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        sexComboBox = new javax.swing.JComboBox();
        stateTextField = new javax.swing.JTextField();
        townTextField = new javax.swing.JTextField();
        districtTextField = new javax.swing.JTextField();
        streetTextField = new javax.swing.JTextField();
        buildingTextField = new javax.swing.JTextField();
        flatTextField = new javax.swing.JTextField();
        homeTextField = new javax.swing.JTextField();
        workplaceTextField = new javax.swing.JTextField();
        homePhoneTextField = new javax.swing.JTextField();
        mobilePhoneTextField = new javax.swing.JTextField();
        workPhoneTextField = new javax.swing.JTextField();
        medicalInsuranceNumberTextField = new javax.swing.JTextField();
        medicalInsuranceSeriesTextField = new javax.swing.JTextField();
        contractTermEndingFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        contractValidityBeginningFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        medicalCardNumberTextField = new javax.swing.JTextField();
        medicalCardDateFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        addEntityButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameTextField.setText("firstNameTextField");

        middleNameTextField.setText("middleNameTextField");

        lastNameTextField.setText("lastNameTextField");
        lastNameTextField.setToolTipText("");

        birthdayDateFormattedTextField.setColumns(15);
        birthdayDateFormattedTextField.setValue(new Date());

        registrationDateFormattedTextField.setColumns(15);
        registrationDateFormattedTextField.setValue(new Date());

        sexComboBox.setModel(new ru.fedul0x.ip.view.component.SexComboBoxModel());
        sexComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexComboBoxActionPerformed(evt);
            }
        });

        stateTextField.setText("stateTextField");

        townTextField.setText("townTextField");

        districtTextField.setText("districtTextField");

        streetTextField.setText("streetTextField");

        buildingTextField.setText("buildingTextField");

        flatTextField.setText("flatTextField");
        flatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatTextFieldActionPerformed(evt);
            }
        });

        homeTextField.setText("homeTextField");
        homeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeTextFieldActionPerformed(evt);
            }
        });

        workplaceTextField.setText("workplaceTextField");

        homePhoneTextField.setText("homePhoneTextField");

        mobilePhoneTextField.setText("mobilePhoneTextField");

        workPhoneTextField.setText("workPhoneTextField");
        workPhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workPhoneTextFieldActionPerformed(evt);
            }
        });

        medicalInsuranceNumberTextField.setText("medicalInsuranceNumberTextField");
        medicalInsuranceNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalInsuranceNumberTextFieldActionPerformed(evt);
            }
        });

        medicalInsuranceSeriesTextField.setText("medicalInsuranceSeriesTextField");

        contractTermEndingFormattedTextField.setColumns(15);
        contractTermEndingFormattedTextField.setValue(new Date());
        contractTermEndingFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy, EEEE"))));

        contractValidityBeginningFormattedTextField.setColumns(15);
        contractValidityBeginningFormattedTextField.setValue(new Date());
        contractValidityBeginningFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy, EEEE"))));

        medicalCardNumberTextField.setText("medicalCardNumberTextField");
        medicalCardNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalCardNumberTextFieldActionPerformed(evt);
            }
        });

        medicalCardDateFormattedTextField.setColumns(15);
        medicalCardDateFormattedTextField.setValue(new Date());
        medicalCardDateFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy, EEEE"))));
        medicalCardDateFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalCardDateFormattedTextFieldActionPerformed(evt);
            }
        });

        addEntityButton.setText("addEntityButton");
        addEntityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(middleNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthdayDateFormattedTextField)
                            .addComponent(registrationDateFormattedTextField)
                            .addComponent(sexComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mobilePhoneTextField)
                            .addComponent(stateTextField)
                            .addComponent(townTextField)
                            .addComponent(districtTextField)
                            .addComponent(streetTextField)
                            .addComponent(buildingTextField)
                            .addComponent(flatTextField)
                            .addComponent(homeTextField)
                            .addComponent(workplaceTextField)
                            .addComponent(homePhoneTextField)
                            .addComponent(workPhoneTextField))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(medicalInsuranceNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contractTermEndingFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contractValidityBeginningFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(medicalCardNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(medicalCardDateFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(medicalInsuranceSeriesTextField))
                            .addComponent(addEntityButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(townTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(medicalInsuranceSeriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(medicalInsuranceNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(districtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(birthdayDateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(registrationDateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buildingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(flatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(workplaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mobilePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contractTermEndingFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contractValidityBeginningFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(medicalCardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(medicalCardDateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addEntityButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sexComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexComboBoxActionPerformed

    private void flatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flatTextFieldActionPerformed

    private void workPhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workPhoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workPhoneTextFieldActionPerformed

    private void homeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeTextFieldActionPerformed

    private void medicalInsuranceNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalInsuranceNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalInsuranceNumberTextFieldActionPerformed

    private void medicalCardNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalCardNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalCardNumberTextFieldActionPerformed

    private void addEntityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntityButtonActionPerformed
        try {
            // TODO add your handling code here:
            DateFormat format = new SimpleDateFormat("dd MMMM yyyy, EEEE");
            Date bd = format.parse((String) birthdayDateFormattedTextField.getText());
            Date rd = format.parse((String) registrationDateFormattedTextField.getText());
            Date cte = format.parse((String) contractTermEndingFormattedTextField.getText());

            Date cvb = format.parse((String) contractValidityBeginningFormattedTextField.getText());
            Date mcd = format.parse((String) medicalCardDateFormattedTextField.getText());

            Patient patient = new Patient(2L);
            patient.setFirstName(firstNameTextField.getText());
            patient.setLastName(lastNameTextField.getText());
            patient.setMiddleName(middleNameTextField.getText());
            patient.setBirthdayDate(bd);
            patient.setRegistrationDate(rd);
    //TODO correct this error
            patient.setSex(false);
            patient.setSex(((SexComboBoxModel)sexComboBox.getModel()).getValue());
            patient.setState(stateTextField.getText());
            patient.setTown(townTextField.getText());
            patient.setDistrict(districtTextField.getText());
            patient.setStreet(streetTextField.getText());
            patient.setBuilding(buildingTextField.getText());
            patient.setFlat(flatTextField.getText());
            patient.setHome(homeTextField.getText());
            patient.setWorkplace(workplaceTextField.getText());
            patient.setHomePhone(homePhoneTextField.getText());
            patient.setMobilePhone(mobilePhoneTextField.getText());
            patient.setWorkPhone(workPhoneTextField.getText());
            patient.setMedicalInsuranceSeries(medicalInsuranceSeriesTextField.getText());
            patient.setMedicalInsuranceNumber(medicalInsuranceNumberTextField.getText());
            patient.setContractTermEnding(cte);
            patient.setContractValidityBeginning(cvb);
            patient.setMedicalCardNumber(medicalCardNumberTextField.getText());
            patient.setMedicalCardDate(mcd);
//            DataSourceRepository.getDataSource(Patient.class).makePersistent(patient);
            DataSourceHibernate<Patient> dsh = new DataSourceHibernate<Patient>();
            dsh.makePersistent(patient);
            dsh.flush();
        } catch (ParseException ex) {
            Logger.getLogger(PatienAddFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addEntityButtonActionPerformed

    private void medicalCardDateFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalCardDateFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalCardDateFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatienAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatienAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatienAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatienAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
// birthdayDateTextField    new PatienAddFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEntityButton;
    private javax.swing.JFormattedTextField birthdayDateFormattedTextField;
    private javax.swing.JTextField buildingTextField;
    private javax.swing.JFormattedTextField contractTermEndingFormattedTextField;
    private javax.swing.JFormattedTextField contractValidityBeginningFormattedTextField;
    private javax.swing.JTextField districtTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField flatTextField;
    private javax.swing.JTextField homePhoneTextField;
    private javax.swing.JTextField homeTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JFormattedTextField medicalCardDateFormattedTextField;
    private javax.swing.JTextField medicalCardNumberTextField;
    private javax.swing.JTextField medicalInsuranceNumberTextField;
    private javax.swing.JTextField medicalInsuranceSeriesTextField;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JTextField mobilePhoneTextField;
    private javax.swing.JFormattedTextField registrationDateFormattedTextField;
    private javax.swing.JComboBox sexComboBox;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JTextField townTextField;
    private javax.swing.JTextField workPhoneTextField;
    private javax.swing.JTextField workplaceTextField;
    // End of variables declaration//GEN-END:variables
}
