package ip.dataaccess.dataobject;


// Generated 23.12.2012 2:11:14 by Hibernate Tools 3.2.1.GA


import ip.dataaccess.dataobject.MedicalConsultation;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name="schedule"
    ,schema="public"
)
public class Schedule  implements java.io.Serializable {


     private int id;
     private Service service;
     private Staff staffByDoctorId;
     private MedicalConsultation medicalConsultation;
     private Staff staffByNurseId;
     private Date serviceRenderingDate;
     private Date serviceRenderingTime;
     private Short shiftNumer;

    public Schedule() {
    }

	
    public Schedule(int id) {
        this.id = id;
    }
    public Schedule(int id, Service service, Staff staffByDoctorId, MedicalConsultation medicalConsultation, Staff staffByNurseId, Date serviceRenderingDate, Date serviceRenderingTime, Short shiftNumer) {
       this.id = id;
       this.service = service;
       this.staffByDoctorId = staffByDoctorId;
       this.medicalConsultation = medicalConsultation;
       this.staffByNurseId = staffByNurseId;
       this.serviceRenderingDate = serviceRenderingDate;
       this.serviceRenderingTime = serviceRenderingTime;
       this.shiftNumer = shiftNumer;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_id")
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctor_id")
    public Staff getStaffByDoctorId() {
        return this.staffByDoctorId;
    }
    
    public void setStaffByDoctorId(Staff staffByDoctorId) {
        this.staffByDoctorId = staffByDoctorId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="medical_consultation_id")
    public MedicalConsultation getMedicalConsultation() {
        return this.medicalConsultation;
    }
    
    public void setMedicalConsultation(MedicalConsultation medicalConsultation) {
        this.medicalConsultation = medicalConsultation;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nurse_id")
    public Staff getStaffByNurseId() {
        return this.staffByNurseId;
    }
    
    public void setStaffByNurseId(Staff staffByNurseId) {
        this.staffByNurseId = staffByNurseId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="service_rendering_date", length=13)
    public Date getServiceRenderingDate() {
        return this.serviceRenderingDate;
    }
    
    public void setServiceRenderingDate(Date serviceRenderingDate) {
        this.serviceRenderingDate = serviceRenderingDate;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="service_rendering_time", length=15)
    public Date getServiceRenderingTime() {
        return this.serviceRenderingTime;
    }
    
    public void setServiceRenderingTime(Date serviceRenderingTime) {
        this.serviceRenderingTime = serviceRenderingTime;
    }
    
    @Column(name="shift_numer")
    public Short getShiftNumer() {
        return this.shiftNumer;
    }
    
    public void setShiftNumer(Short shiftNumer) {
        this.shiftNumer = shiftNumer;
    }




}


