package ru.fedul0x.ip.dataaccess.dataobject;


// Generated 23.12.2012 2:11:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payer generated by hbm2java
 */
@Entity
@Table(name="payer"
    ,schema="public"
)
public class Payer  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String middleName;
     private Date birthdayDate;
     private String passportNumber;
     private String passportSeries;
     private String passportIssuedBy;
     private Set medicalConsultations = new HashSet(0);

    public Payer() {
    }

	
    public Payer(int id) {
        this.id = id;
    }
    public Payer(int id, String firstName, String lastName, String middleName, Date birthdayDate, String passportNumber, String passportSeries, String passportIssuedBy, Set medicalConsultations) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.middleName = middleName;
       this.birthdayDate = birthdayDate;
       this.passportNumber = passportNumber;
       this.passportSeries = passportSeries;
       this.passportIssuedBy = passportIssuedBy;
       this.medicalConsultations = medicalConsultations;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="first_name")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="last_name")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="middle_name")
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="birthday_date", length=13)
    public Date getBirthdayDate() {
        return this.birthdayDate;
    }
    
    public void setBirthdayDate(Date birthdayDate) {
        this.birthdayDate = birthdayDate;
    }
    
    @Column(name="passport_number", length=6)
    public String getPassportNumber() {
        return this.passportNumber;
    }
    
    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
    }
    
    @Column(name="passport_series", length=4)
    public String getPassportSeries() {
        return this.passportSeries;
    }
    
    public void setPassportSeries(String passportSeries) {
        this.passportSeries = passportSeries;
    }
    
    @Column(name="passport_issued_by", length=100)
    public String getPassportIssuedBy() {
        return this.passportIssuedBy;
    }
    
    public void setPassportIssuedBy(String passportIssuedBy) {
        this.passportIssuedBy = passportIssuedBy;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="payer")
    public Set getMedicalConsultations() {
        return this.medicalConsultations;
    }
    
    public void setMedicalConsultations(Set medicalConsultations) {
        this.medicalConsultations = medicalConsultations;
    }




}


