package ru.fedul0x.ip.dataaccess.dataobject;


// Generated 23.12.2012 2:11:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name="payment_method"
    ,schema="public"
)
public class PaymentMethod  implements java.io.Serializable {


     private int id;
     private String paymentMethodName;
     private String description;
     private Set medicalConsultations = new HashSet(0);

    public PaymentMethod() {
    }

	
    public PaymentMethod(int id) {
        this.id = id;
    }
    public PaymentMethod(int id, String paymentMethodName, String description, Set medicalConsultations) {
       this.id = id;
       this.paymentMethodName = paymentMethodName;
       this.description = description;
       this.medicalConsultations = medicalConsultations;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="payment_method_name")
    public String getPaymentMethodName() {
        return this.paymentMethodName;
    }
    
    public void setPaymentMethodName(String paymentMethodName) {
        this.paymentMethodName = paymentMethodName;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="paymentMethod")
    public Set getMedicalConsultations() {
        return this.medicalConsultations;
    }
    
    public void setMedicalConsultations(Set medicalConsultations) {
        this.medicalConsultations = medicalConsultations;
    }




}


