package ru.fedul0x.ip.dataaccess.dataobject;

// Generated 23.12.2012 2:11:14 by Hibernate Tools 3.2.1.GA
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import ru.fedul0x.ip.dataaccess.DataEntity;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", schema = "public")
public class Service extends DataEntity {

//     private Long id;
    private String serviceName;
    private Short serviceCodeMajor;
    private Short serviceCodeMinor;
    private Short timeSpent;
    private Double monthlyNorm;
    private Set servicePrices = new HashSet(0);
    private Set schedules = new HashSet(0);
    private Set medicalConsultations = new HashSet(0);

    public Service() {
    }

    public Service(Long id) {
        this.id = id;
    }

    public Service(Long id, String serviceName, Short serviceCodeMajor, Short serviceCodeMinor, Short timeSpent, Double monthlyNorm, Set servicePrices, Set schedules, Set medicalConsultations) {
        this.id = id;
        this.serviceName = serviceName;
        this.serviceCodeMajor = serviceCodeMajor;
        this.serviceCodeMinor = serviceCodeMinor;
        this.timeSpent = timeSpent;
        this.monthlyNorm = monthlyNorm;
        this.servicePrices = servicePrices;
        this.schedules = schedules;
        this.medicalConsultations = medicalConsultations;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "service_name")
    public String getServiceName() {
        return this.serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    @Column(name = "service_code_major")
    public Short getServiceCodeMajor() {
        return this.serviceCodeMajor;
    }

    public void setServiceCodeMajor(Short serviceCodeMajor) {
        this.serviceCodeMajor = serviceCodeMajor;
    }

    @Column(name = "service_code_minor")
    public Short getServiceCodeMinor() {
        return this.serviceCodeMinor;
    }

    public void setServiceCodeMinor(Short serviceCodeMinor) {
        this.serviceCodeMinor = serviceCodeMinor;
    }

    @Column(name = "time_spent")
    public Short getTimeSpent() {
        return this.timeSpent;
    }

    public void setTimeSpent(Short timeSpent) {
        this.timeSpent = timeSpent;
    }

    @Column(name = "monthly_norm", precision = 17, scale = 17)
    public Double getMonthlyNorm() {
        return this.monthlyNorm;
    }

    public void setMonthlyNorm(Double monthlyNorm) {
        this.monthlyNorm = monthlyNorm;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "service")
    public Set getServicePrices() {
        return this.servicePrices;
    }

    public void setServicePrices(Set servicePrices) {
        this.servicePrices = servicePrices;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "service")
    public Set getSchedules() {
        return this.schedules;
    }

    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "service")
    public Set getMedicalConsultations() {
        return this.medicalConsultations;
    }

    public void setMedicalConsultations(Set medicalConsultations) {
        this.medicalConsultations = medicalConsultations;
    }
}
