package ru.fedul0x.ip.dataaccess.dataobject;


// Generated 23.12.2012 2:11:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name="system_user"
    ,schema="public"
)
public class SystemUser  implements java.io.Serializable {


     private int id;
     private Staff staff;
     private String login;
     private String hashpass;
     private Set medicalConsultations = new HashSet(0);

    public SystemUser() {
    }

	
    public SystemUser(int id) {
        this.id = id;
    }
    public SystemUser(int id, Staff staff, String login, String hashpass, Set medicalConsultations) {
       this.id = id;
       this.staff = staff;
       this.login = login;
       this.hashpass = hashpass;
       this.medicalConsultations = medicalConsultations;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="staff")
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    
    @Column(name="login")
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="hashpass")
    public String getHashpass() {
        return this.hashpass;
    }
    
    public void setHashpass(String hashpass) {
        this.hashpass = hashpass;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="systemUser")
    public Set getMedicalConsultations() {
        return this.medicalConsultations;
    }
    
    public void setMedicalConsultations(Set medicalConsultations) {
        this.medicalConsultations = medicalConsultations;
    }




}


