package ip.dataaccess;
// Generated 23.12.2012 2:11:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StaffPosition generated by hbm2java
 */
@Entity
@Table(name="staff_position"
    ,schema="public"
)
public class StaffPosition  implements java.io.Serializable {


     private int id;
     private String staffPositionName;
     private String description;
     private Set staffs = new HashSet(0);

    public StaffPosition() {
    }

	
    public StaffPosition(int id) {
        this.id = id;
    }
    public StaffPosition(int id, String staffPositionName, String description, Set staffs) {
       this.id = id;
       this.staffPositionName = staffPositionName;
       this.description = description;
       this.staffs = staffs;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="staff_position_name")
    public String getStaffPositionName() {
        return this.staffPositionName;
    }
    
    public void setStaffPositionName(String staffPositionName) {
        this.staffPositionName = staffPositionName;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="staffPosition")
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


